version: "2"
services:

  mongors1n1:
    container_name: mongors1n1
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --port 27018 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors1n1:/data/db

  mongors1n2:
    container_name: mongors1n2
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --port 27018 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors1n2:/data/db

  mongors1n3:
    container_name: mongors1n3
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --port 27018 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors1n3:/data/db

  mongors2n1:
    container_name: mongors2n1
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --port 27018  --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors2n1:/data/db

  mongors2n2:
    container_name: mongors2n2
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --port 27018 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors2n2:/data/db

  mongors2n3:
    container_name: mongors2n3
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --port 27018 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors2n3:/data/db

  mongocfg1:
    container_name: mongocfg1
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --replSet mongocfg --noauth --port 27019
    environment:
      TERM: xterm
    expose:
         - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongocfg1:/data/db

  mongocfg2:
    container_name: mongocfg2
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --replSet mongocfg --noauth --port 27019
    environment:
      TERM: xterm
    expose:
         - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongocfg2:/data/db

  mongocfg3:
    container_name: mongocfg3
    image: mongo:3.4
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --replSet mongocfg --noauth --port 27019
    environment:
      TERM: xterm
    expose:
         - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongocfg3:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.4
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongocfg/mongocfg1:27019,mongocfg2:27019,mongocfg3:27019 --port 27017
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mongocli:
    container_name: mongocli
    image: mongoclient/mongoclient:2.0.0
    depends_on:
      - mongos1
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongoclient:/data/db

