version: "2"
services:

  mongors1n1:
    container_name: mongors1n1
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --port 27018 --dbpath /data/db --nojournal --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongors1n1:/data/db
    networks:
      - backend

  mongors1n2:
    container_name: mongors1n2
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --port 27018 --dbpath /data/db --nojournal --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongors1n2:/data/db
    networks:
      - backend

  mongors1n3:
    container_name: mongors1n3
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --port 27018 --dbpath /data/db --nojournal --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongors1n3:/data/db
    networks:
      - backend

  mongors2n1:
    container_name: mongors2n1
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --port 27018  --dbpath /data/db --nojournal --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongors2n1:/data/db
    networks:
      - backend

  mongors2n2:
    container_name: mongors2n2
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --port 27018 --dbpath /data/db --nojournal --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongors2n2:/data/db
    networks:
      - backend

  mongors2n3:
    container_name: mongors2n3
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --port 27018 --dbpath /data/db --nojournal --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongors2n3:/data/db
    networks:
      - backend

  mongocfg1:
    container_name: mongocfg1
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --replSet mongocfg --noauth --port 27019
    environment:
      TERM: xterm
    expose:
         - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongocfg1:/data/db
    networks:
      - backend

  mongocfg2:
    container_name: mongocfg2
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --replSet mongocfg --noauth --port 27019
    environment:
      TERM: xterm
    expose:
         - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongocfg2:/data/db
    networks:
      - backend

  mongocfg3:
    container_name: mongocfg3
    restart: on-failure
    image: mongo
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --replSet mongocfg --noauth --port 27019
    environment:
      TERM: xterm
    expose:
         - "27019"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mongo-docker-compose/data/mongocfg3:/data/db
    networks:
      - backend

  mongos1:
    container_name: mongos1
    restart: on-failure
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongocfg/mongocfg1:27019,mongocfg2:27019,mongocfg3:27019 --port 27017
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
    internal: yes
  frontend:
    driver: bridge
